name: Build Patched APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download Apktool
      run: |
        wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
        sudo mv apktool.jar /usr/local/bin/apktool.jar
        echo '#!/bin/bash' | sudo tee /usr/local/bin/apktool
        echo 'java -jar /usr/local/bin/apktool.jar "$@"' | sudo tee -a /usr/local/bin/apktool
        sudo chmod +x /usr/local/bin/apktool

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'platform-tools build-tools;34.0.0'

    # setup-android action doesnt add buildtools to the PATH, so we do manually
    - name: Add Android Build Tools to PATH
      run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
      shell: bash

    - name: Decompile APK
      run: apktool d source_apk/ru.oneme.app.apk -f -o apk_workdir

    # prevents java.util.zip.ZipException: duplicate entry: stamp-cert-sha256
    - name: Remove original signature
      run: |
        rm -rf apk_workdir/original/META-INF
        rm -rf apk_workdir/original/stamp-cert-sha256

    - name: Upload as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk_workdir
        path: apk_workdir