name: Build and Patch OLDER VERSIONS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run workflow on"
        required: true
      workflow:
        description: "Workflow filename to run"
        required: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger selected workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: ${{ github.event.inputs.workflow }}
          ref: ${{ github.event.inputs.branch }}
